services:
  postgres:
    image: postgres:latest
    container_name: syllabusmatcherai_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - syllabusmatcherai_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syllabusmatcherai_fastapi
    entrypoint: ["./wait_for_db.sh", "postgres:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - syllabusmatcherai_network
    env_file:
      - .env

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syllabusmatcherai_alembic
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - syllabusmatcherai_network
    depends_on:
      - postgres
    entrypoint: ["./wait_for_db.sh", "postgres:5432", "--", "alembic", "upgrade", "head"]
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  syllabusmatcherai_network:
    driver: bridge